# Site settings
title: Grimoire
author: Saph
description:
  A searchable d20 5e spell list, sorted by class and level.
baseurl: /grimoire # the subpath of your site, e.g. /blog/
url: ephe.github.io # the base hostname & protocol for your site
source-url: https://github.com/ephe/grimoire/
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"